# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: py_video_gunner/grpc_stream/grpc_video/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1py_video_gunner/grpc_stream/grpc_video/data.proto\x12+py_video_gunner.grpc_stream.grpc_video.data\"\x15\n\x05\x43hunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\tb\x06proto3')



_CHUNK = DESCRIPTOR.message_types_by_name['Chunk']
Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'py_video_gunner.grpc_stream.grpc_video.data_pb2'
  # @@protoc_insertion_point(class_scope:py_video_gunner.grpc_stream.grpc_video.data.Chunk)
  })
_sym_db.RegisterMessage(Chunk)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHUNK._serialized_start=98
  _CHUNK._serialized_end=119
# @@protoc_insertion_point(module_scope)
