# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_video/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_video import data_pb2 as grpc__video_dot_data__pb2
from grpc_video import response_pb2 as grpc__video_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpc_video/service.proto\x12\x12grpc_video.service\x1a\x15grpc_video/data.proto\x1a\x19grpc_video/response.proto2V\n\x0bVideoUpload\x12G\n\x06Upload\x12\x16.grpc_video.data.Chunk\x1a!.grpc_video.response.UploadStatus\"\x00(\x01\x62\x06proto3')



_VIDEOUPLOAD = DESCRIPTOR.services_by_name['VideoUpload']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOUPLOAD._serialized_start=98
  _VIDEOUPLOAD._serialized_end=184
# @@protoc_insertion_point(module_scope)
